/*
 * Parallax Mouse Interaction v1.5
 *
 * Copyright 2012-2017, LambertGroup
 * 
*/


(function(c){function Z(a,b,d){var h=S();d.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(d.origWidth/d.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(d.origWidth/d.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,
a.css("line-height").lastIndexOf("px")),newCss+="line-height:"+lineHeight/(d.origWidth/d.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(d.origWidth/d.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var f,n,l;f=a.attr("data-final-left");n=a.attr("data-final-top");d.responsive&&(f=parseInt(f/(d.origWidth/d.width),10),n=parseInt(n/(d.origWidth/d.width),
10));if("true"!=a.attr("data-preanimate")){var g=d.defaultEasing;""!=a.attr("data-easing")&&void 0!=a.attr("data-easing")&&(g=a.attr("data-easing"));l=1;1==b.isVideoPlaying&&(l=0);-1!=h&&9>h&&a.css({opacity:1});a.stop().animate({opacity:l,left:f+"px",top:n+"px"},1E3*a.attr("data-duration"),g,function(){1==b.isVideoPlaying&&c(b.currentImg.attr("data-text-id")).children().css("opacity",0);b.textInPlace[b.textInPlace.length]=1;void 0!=a.attr("data-continuous-left")&&""!=a.attr("data-continuous-left")&&
(L(a,b,d),b.continuouseIntervalIDs[b.continuouseIntervalIDs.length]=setInterval(function(){L(a,b,d)},1E3*a.attr("data-continuous-duration")));(-1==h||-1!=h&&9<=h)&&void 0!=a.attr("data-rotate")&&""!=a.attr("data-rotate")&&"true"==a.attr("data-rotate")&&(rotDuration=.5,void 0!=a.attr("data-rotate-duration")&&""!=a.attr("data-rotate-duration")&&(rotDuration=a.attr("data-rotate-duration")),b.rotationDurationArr[a.index()]=rotDuration,b.rotationFunctionsArr[a.index()]=function(){b.rotationFunctionsArr.length&&
void 0!=b.rotationDurationArr[a.index()]&&""!=b.rotationDurationArr[a.index()]&&a.rotate({angle:0,animateTo:360,duration:1E3*b.rotationDurationArr[a.index()],callback:b.rotationFunctionsArr[a.index()],easing:function(a,b,c,d,f){return b/f*d}})},b.rotationFunctionsArr[a.index()]())})}else a.css({left:f+"px",top:n+"px",opacity:1}),b.textInPlace[b.textInPlace.length]=1}function N(a,b,d,h,f,n,l){b=c(b.attr("data-text-id")).children();var g,q,t=0;currentText_arr=[];l?c(".newFS",f).contents().unwrap():
a.textInPlace.length=0;b.each(function(){currentText_arr[t]=c(this);var b=currentText_arr[t];l&&"true"==b.attr("data-preanimate")?(b.css({display:"block"}),g=b.attr("data-final-left"),q=b.attr("data-final-top"),d.responsive&&(g=parseInt(g/(d.origWidth/d.width),10),q=parseInt(q/(d.origWidth/d.width),10)),b.css({left:g+"px",top:q+"px",opacity:1,display:"block"})):l?b.css({display:"none",opacity:0}):b.css({display:"block"});"true"!=b.attr("data-preanimate")&&(g=b.attr("data-initial-left"),q=b.attr("data-initial-top"),
d.responsive&&(g=parseInt(g/(d.origWidth/d.width),10),q=parseInt(q/(d.origWidth/d.width),10)),b.css({left:g+"px",top:q+"px",opacity:parseInt(b.attr("data-fade-start"),10)/100}));l||(a.timeouts_arr[a.timeouts_arr.length]=setTimeout(function(){Z(b,a,d)},1E3*b.attr("data-delay")));t++})}function L(a,b,c){b=parseInt(a.css("margin-left").substr(0,a.css("margin-left").lastIndexOf("px")),10);var d=parseInt(a.css("margin-top").substr(0,a.css("margin-top").lastIndexOf("px")),10),f=0,n=0;a.attr("data-final-left")!=
a.attr("data-continuous-left")?b>=f-2&&b<=f+2&&(f=parseInt(a.attr("data-continuous-left")/(c.origWidth/c.width),10)-parseInt(a.attr("data-final-left")/(c.origWidth/c.width),10),n=parseInt(a.attr("data-continuous-top")/(c.origWidth/c.width),10)-parseInt(a.attr("data-final-top")/(c.origWidth/c.width),10)):a.attr("data-final-top")!=a.attr("data-continuous-top")&&d>=n-2&&d<=n+2&&(f=parseInt(a.attr("data-continuous-left")/(c.origWidth/c.width),10)-parseInt(a.attr("data-final-left")/(c.origWidth/c.width),
10),n=parseInt(a.attr("data-continuous-top")/(c.origWidth/c.width),10)-parseInt(a.attr("data-final-top")/(c.origWidth/c.width),10));a.stop().animate({"margin-left":f+"px","margin-top":n+"px"},1E3*a.attr("data-continuous-duration"),a.attr("data-continuous-easing"),function(){})}function aa(a,b,d,h){d=c(a.currentImg.attr("data-text-id")).children();var f=0;currentText_arr=[];d.each(function(){currentText_arr[f]=c(this);var d=currentText_arr[f],h=b.defaultExitLeft;void 0!=d.attr("data-exit-left")&&""!=
d.attr("data-exit-left")&&(h=parseInt(d.attr("data-exit-left")/(b.origWidth/b.width),10));var g=b.defaultExitTop;void 0!=d.attr("data-exit-top")&&""!=d.attr("data-exit-top")&&(g=parseInt(d.attr("data-exit-top")/(b.origWidth/b.width),10));var q=b.defaultExitDuration;void 0!=d.attr("data-exit-duration")&&""!=d.attr("data-exit-duration")&&(q=parseFloat(d.attr("data-exit-duration")));var t=b.defaultExitDelay;void 0!=d.attr("data-exit-delay")&&""!=d.attr("data-exit-delay")&&(t=parseFloat(d.attr("data-exit-delay")));
var w=b.defaultExitEasing;void 0!=d.attr("data-exit-easing")&&""!=d.attr("data-exit-easing")&&(w=d.attr("data-exit-easing"));var m=b.defaultExitOFF.toString();void 0!=d.attr("data-exit-off")&&""!=d.attr("data-exit-off")&&(m=d.attr("data-exit-off"));"true"==m&&(q=0);0<q?a.timeouts_arr[a.timeouts_arr.length]=setTimeout(function(){d.stop().animate({left:h+"px",top:g+"px"},1E3*q,w,function(){"true"!=d.attr("data-preanimate")&&"false"==m?d.css({display:"none"}):(theLeft=d.attr("data-final-left"),theTop=
d.attr("data-final-top"),b.responsive&&(theLeft=parseInt(theLeft/(b.origWidth/b.width),10),theTop=parseInt(theTop/(b.origWidth/b.width),10)),d.css({left:theLeft+"px",top:theTop+"px",opacity:1}))})},1E3*t):"true"!=d.attr("data-preanimate")&&"false"==m&&d.css({display:"none"});f++})}function V(a,b,d,h){for(k=0;k<h;k++)d=c(a[k]),d=c(d.attr("data-text-id")).children(),currentText_arr=[],d.each(function(){currentText_arr[0]=c(this);var a=currentText_arr[0];if("true"==a.attr("data-preanimate")){a.css({display:"block"});
var d=a.attr("data-final-left"),h=a.attr("data-final-top");b.responsive&&(d=parseInt(d/(b.origWidth/b.width),10),h=parseInt(h/(b.origWidth/b.width),10));a.css({left:d+"px",top:h+"px",opacity:1})}else a.css({display:"none"})})}function M(a){if(a)for(var b in a)a[b]&&clearTimeout(a[b]);a.length=0}function W(a){if(a)for(var b in a)a[b]&&clearInterval(a[b]);a.length=0}function ba(a,b){if(a)for(var c in a)a[c]&&(a[c]=function(){});a.length=0;b.rotationDurationArr.length=0}function ca(a,b,d,h,f){var n=
c(b.attr("data-text-id")).children();if(a.textInPlace.length==n.length&&(0!=h||0!=f)){var l=1,g,q=!0;n.each(function(){g=c(this);q=!0;"false"==g.attr("data-enableMouseInteraction")&&(q=!1);q&&g.stop().animate({left:parseInt(g.attr("data-final-left")/(d.origWidth/d.width),10)+parseInt(h*l/n.length,10)+"px",top:parseInt(g.attr("data-final-top")/(d.origWidth/d.width),10)+parseInt(f*l/n.length,10)+"px"},{queue:!0,duration:1E3*d.mouseInteractionDuration,easing:d.mouseInteractionEasing},function(){});l++})}}
function H(a,b,d,h,f,n,l,g,q,t,w,m,A,D,G,u,I,y){var v=!0,x;if(!d.loop&&b.current_img_no+a>=h||!d.loop&&0>b.current_img_no+a)v=!1;v&&!b.slideIsRunning&&b.firstLoadingComplete&&(b.slideIsRunning=!0,M(b.timeouts_arr),W(b.continuouseIntervalIDs),ba(b.rotationFunctionsArr,b),b.textInPlace.length=0,x=b.previous_current_img_no,c(b.currentImg.attr("data-text-id")).children().clearQueue(),aa(b,d,l,g),d.showCircleTimer&&(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=
d.behindCircleAlpha/100,b.ctx.arc(d.circleRadius+2*d.circleLineWidth,d.circleRadius+2*d.circleLineWidth,d.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=d.circleLineWidth+2,b.ctx.strokeStyle=d.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=d.circleAlpha/100,b.ctx.arc(d.circleRadius+2*d.circleLineWidth,d.circleRadius+2*d.circleLineWidth,d.circleRadius,0,0,!1),b.ctx.lineWidth=d.circleLineWidth,b.ctx.strokeStyle=d.circleColor,b.ctx.stroke()),"bullets"==d.skin?c(f[b.current_img_no]).removeClass("bottomNavButtonON"):
c(m[b.current_img_no]).removeClass("thumbsHolder_ThumbON"),w.css("display","none"),b.current_img_no=b.current_img_no+a>=h?0:0>b.current_img_no+a?h-1:b.current_img_no+a,d.showBottomNav&&("bullets"==d.skin?(d.autoHideBottomNav||y.css("display","block"),c(f[b.current_img_no]).addClass("bottomNavButtonON")):(d.autoHideBottomNav||I.css("display","block"),c(m[b.current_img_no]).addClass("thumbsHolder_ThumbON"),currentCarouselLeft=A.css("left").substr(0,A.css("left").lastIndexOf("px")),0===b.current_img_no||
b.current_img_no===h-1?O(0,A,D,G,d,h,u,b):O(1001,A,D,G,d,h,u,b))),b.currentImg=c(n[b.current_img_no]),q.animate({left:-1*b.current_img_no*d.width+"px"},1E3*d.scrollSlideDuration,d.scrollSlideEasing,function(){b.slideIsRunning=!1;b.arcInitialTime=(new Date).getTime();b.timeElapsed=0;"true"==c(n[b.current_img_no]).attr("data-video")&&w.css("display","block");"true"==c(n[b.previous_current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+b.previous_current_img_no,t).html(c(n[b.previous_current_img_no]).html()),
P(b.previous_current_img_no,b,d,n,t,l,g));M(b.timeouts_arr);N(b,c(n[x]),d,l,t,g,!0);N(b,b.currentImg,d,l,t,g,!1);0<d.autoPlay&&1<h&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),b.timeoutID=setTimeout(function(){b.previous_current_img_no=b.current_img_no;H(1,b,d,h,f,n,l,g,q,t,w,m,A,D,G,u,I,y)},1E3*d.autoPlay))}))}function Q(a,b,c,h,f){b=c.origImgsDimensions[b].split(";");h.responsive&&(b[0]/=h.origWidth/h.width,b[1]/=h.origWidth/h.width);a.width(b[0]);a.height(b[1]);f&&h.width100Proc&&h.height100Proc&&
a.css({position:"relative",left:parseInt(h.width-a.width(),10)+"px",top:parseInt(h.height-a.height(),10)+"px"})}function P(a,b,d,h,f,n,l){d.responsive&&(imgInside=c("#contentHolderUnit_"+a,f).find("img:first"),null!=imgInside.width()&&Q(imgInside,a,b,d,!0),textIdChildren=c(c(h[a]).attr("data-text-id")).children(),k=-1,textIdChildren.each(function(){k++;imgInside=c(this).find("img:first");null!=imgInside.width()&&Q(imgInside,c(h[a]).attr("data-text-id")+"-"+k,b,d,!1)}),c(c(h[a]).attr("data-text-id")).css({width:d.width+
"px",left:parseInt(a*d.width,10),top:l.css("top")}))}function O(a,b,c,h,f,n,l,g){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?(g.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:"+="+a*g.carouselStep},500,"easeOutCubic",function(){X(g,b,c,h,f,n,l);g.isCarouselScrolling=!1})):currentCarouselLeft!=-1*Math.floor(g.current_img_no/f.numberOfThumbsPerScreen)*g.carouselStep&&(g.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,
left:-1*Math.floor(g.current_img_no/f.numberOfThumbsPerScreen)*g.carouselStep},500,"easeOutCubic",function(){X(g,b,c,h,f,n,l);g.isCarouselScrolling=!1}))}function X(a,b,c,h,f,n,l){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>currentCarouselLeft?c.hasClass("carouselLeftNavDisabled")&&c.removeClass("carouselLeftNavDisabled"):c.addClass("carouselLeftNavDisabled");Math.abs(currentCarouselLeft-a.carouselStep)<(l.width()+a.thumbMarginLeft)*n?h.hasClass("carouselRightNavDisabled")&&
h.removeClass("carouselRightNavDisabled"):h.addClass("carouselRightNavDisabled")}function Y(a,b,d,h,f,n,l,g,q,t,w){"thumbs"==b.skin&&(w.css({bottom:parseInt(b.thumbsWrapperMarginBottom/(b.origWidth/b.width),10)+"px",top:"auto",height:parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)+"px"}),bgTopCorrection=0,l.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),g.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+
"px"),t.css("width",b.width-l.width()-g.width()),b.origWidthThumbsHolderVisibleWrapper=b.origWidth-l.width()-g.width(),f.css({width:parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/t.width()),10)+"px",height:parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/t.width()),10)+"px"}),b.numberOfThumbsPerScreen>=d&&t.css("left",parseInt((w.width()-(q.width()+a.thumbMarginLeft)*d)/2,10)+"px"),c(".thumbsHolder_ThumbOFF",h).find("img:first").css({width:f.width()+"px",height:f.height()+
"px","margin-top":parseInt((w.height()-f.height())/2,10)+"px"}),a.thumbMarginLeft=Math.floor((w.width()-l.width()-g.width()-q.width()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),thumb_i=-1,n.children().each(function(){thumb_i++;theThumb=c(this);theThumb.css("background-position","center "+b.thumbsOnMarginTop/(b.origWidth/b.width)+"px");0>=thumb_i?theThumb.css("margin-left",Math.floor((w.width()-l.width()-g.width()-(a.thumbMarginLeft+theThumb.width())*(b.numberOfThumbsPerScreen-1)-theThumb.width())/
2)+"px"):theThumb.css("margin-left",a.thumbMarginLeft+"px")}),a.carouselStep=(q.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen)}function S(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}c.fn.parallax_mouseinteraction=function(a){a=c.extend({},c.fn.parallax_mouseinteraction.defaults,a);return this.each(function(){var b=c(this);responsiveWidth=b.parent().width();responsiveHeight=
b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/a.origHeight)));var d=c("<div></div>").addClass("parallax_mouseinteraction").addClass(a.skin),
h=c('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolderVisibleWrapper"><div class="contentHolder"></div></div>   <div class="playOver"></div>  <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <canvas class="mycanvas"></canvas>');b.wrap(d);b.after(h);var f=b.parent(".parallax_mouseinteraction"),h=c(".bannerControls",f),n=c(".contentHolderVisibleWrapper",
f),l=c(".contentHolder",f),d=c('<div class="bottomNavLeft"></div>'),g=c('<div class="bottomNav"></div>'),q=c('<div class="bottomNavRight"></div>');b.after(d);b.after(g);b.after(q);a.showAllControllers||h.css("display","none");var t=c(".leftNav",f),w=c(".rightNav",f);t.css("display","none");w.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(t.css("display","block"),w.css("display","block"));var m=c(".bottomNav",f),A=c(".bottomNavLeft",f),D=c(".bottomNavRight",f),G;m.css("display","block");
A.css("display","block");D.css("display","block");m.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});A.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});D.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});a.showBottomNav||(m.css("display","none"),A.css("display","none"),D.css("display","none"));a.showOnInitBottomNav||(m.css("left","-5000px"),A.css("left","-5000px"),D.css("left",
"-5000px"));var u=c(".thumbsHolderWrapper",f),I=c(".thumbsHolderVisibleWrapper",f),y=c(".thumbsHolder",f),v,x;v=c('<div class="carouselLeftNav"></div>');x=c('<div class="carouselRightNav"></div>');u.append(v);u.append(x);x.css("right","0");y.css("width",v.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||u.css({opacity:0,display:"none"});"thumbs"==a.skin&&u.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});a.enableTouchScreen&&f.swipe({swipe:function(a,
b,c,d,f){e.effectIsRunning||("right"==b?t.click():w.click())}});var B=c(".playOver",f);B.css({left:parseInt((a.width-B.width())/2,10)+"px",top:parseInt((a.height-B.height())/2,10)+"px"});c(".myloader",f).css({left:(a.width-c(".myloader",f).width())/2+"px",top:(a.height-c(".myloader",f).height())/2+"px"});var d=S(),r=0,e={current_img_no:0,currentImg:0,previous_current_img_no:0,slideIsRunning:!1,mouseOverBanner:!1,isVideoPlaying:!1,carouselStep:0,thumbMarginLeft:0,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),
timeElapsed:0,windowWidth:0,origImgsDimensions:[],firstLoadingComplete:!1,canvas:"",ctx:"",timeouts_arr:[],continuouseIntervalIDs:[],rotationFunctionsArr:[],rotationDurationArr:[],textInPlace:[],prevMouseX:0,prevMouseY:0,bannerRatio:a.origWidth/a.origHeight},T=0;e.canvas=c(".mycanvas",f)[0];e.canvas.width=2*a.circleRadius+4*a.circleLineWidth;e.canvas.height=2*a.circleRadius+4*a.circleLineWidth;-1!=d&&9>d&&(a.showCircleTimer=!1);a.showCircleTimer&&(e.ctx=e.canvas.getContext("2d"));f.width(a.width);
f.height(a.height);n.width(a.width);n.height(a.height);l.width(a.width);l.height(a.height);h.css("margin-top",parseInt((a.height-t.height())/2,10)+"px");var p=b.find("ul:first").children(),K,L=0,E,z,R=0,M=0,C;p.each(function(){e.currentImg=c(this);e.currentImg.is("li")||(e.currentImg=e.currentImg.find("li:first"));if(e.currentImg.is("li")){r++;K=c('<div class="contentHolderUnit" rel="'+(r-1)+'" id="contentHolderUnit_'+(r-1)+'">'+e.currentImg.html()+"</div>");K.width(a.width);K.height(a.height);l.append(K);
L+=a.width;C=c("#contentHolderUnit_"+(r-1),f).find("img:first");null!=C.width()?(e.origImgsDimensions[r-1]=C.width()+";"+C.height(),a.responsive&&a.origWidth!=responsiveWidth&&Q(C,r-1,e,a,!0)):e.origImgsDimensions[r-1]=null;"bullets"==a.skin?(E=c('<div class="bottomNavButtonOFF" rel="'+(r-1)+'"></div>'),m.append(E),R+=parseInt(E.css("padding-left").substring(0,E.css("padding-left").length-2),10)+E.width(),M=parseInt((m.height()-parseInt(E.css("height").substring(0,E.css("height").length-2)))/2,10),
E.css("margin-top",M+"px")):(image_name=c(p[r-1]).attr("data-bottom-thumb"),z=c('<div class="thumbsHolder_ThumbOFF" rel="'+(r-1)+'"><img src="'+image_name+'"></div>'),y.append(z),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-v.width()-x.width())/z.width())),a.origThumbW=z.width(),a.origThumbH=z.height(),a.origthumbsHolderWrapperH=u.height(),e.thumbMarginLeft=Math.floor((a.origWidth-v.width()-x.width()-z.width()*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-
1))),y.css("width",y.width()+e.thumbMarginLeft+z.width()+"px"),thumbsHolder_MarginTop=parseInt((u.height()-parseInt(z.css("height").substring(0,z.css("height").length-2)))/2,10));l.append(c(e.currentImg.attr("data-text-id")));c(e.currentImg.attr("data-text-id")).css({width:a.width+"px",height:"100%",overflow:"hidden",left:parseInt((r-1)*a.width,10),top:h.css("top")});var b=-1;c(e.currentImg.attr("data-text-id")).children().each(function(){b++;C=c(this).find("img:first");null!=C.width()?(e.origImgsDimensions[e.currentImg.attr("data-text-id")+
"-"+b]=C.width()+";"+C.height(),a.responsive&&a.origWidth!=responsiveWidth&&Q(C,e.currentImg.attr("data-text-id")+"-"+b,e,a,!1)):e.origImgsDimensions[e.currentImg.attr("data-text-id")+"-"+b]=null})}});l.width(L);"bullets"==a.skin?(m.width(R),a.showOnInitBottomNav&&(m.css("left",parseInt((f.width()-R)/2,10)+"px"),A.css("left",parseInt(m.css("left").substring(0,m.css("left").length-2),10)-A.width()+"px"),D.css("left",parseInt(m.css("left").substring(0,m.css("left").length-2),10)+m.width()+parseInt(E.css("padding-left").substring(0,
E.css("padding-left").length-2),10)+"px"))):(I.css({width:a.origWidth-v.width()-x.width(),left:v.width()+"px"}),e.carouselStep=(z.width()+e.thumbMarginLeft)*a.numberOfThumbsPerScreen,v.addClass("carouselLeftNavDisabled"),a.numberOfThumbsPerScreen>=r&&(x.addClass("carouselRightNavDisabled"),v.css("display","none"),x.css("display","none"),I.css("left",parseInt((u.width()-(z.width()+e.thumbMarginLeft)*r)/2,10)+"px")),c(".thumbsHolder_ThumbOFF",f).find("img:first").css("margin-top",thumbsHolder_MarginTop+
"px"),a.origthumbsHolder_MarginTop=thumbsHolder_MarginTop);thumbsHolder_Thumbs=c(".thumbsHolder_ThumbOFF",f);Y(e,a,r,f,thumbsHolder_Thumbs,y,v,x,z,I,u);1>=r&&(a.showAllControllers=!1,h.css("display","none"),"bullets"==a.skin?(m.css("display","none"),A.css("display","none"),D.css("display","none")):I.css("display","none"),a.enableTouchScreen=!1,l.css({cursor:"default"}));c("iframe",f).each(function(){var a=c(this).attr("src"),b="?wmode=transparent";-1!=a.indexOf("?")&&(b="&wmode=transparent");c(this).attr("src",
a+b)});e.current_img_no=0;e.currentImg=c(p[0]);f.mousemove(function(b){if(a.enableMouseInteraction){var c=parseInt(a.width/2,10),d=parseInt(a.height/2,10),h,J=parseInt(a.maxInteractionXmove/(a.origWidth/a.width)),l=parseInt(a.maxInteractionYmove/(a.origWidth/a.width));h=b.pageX-f.position().left-c;b=b.pageY-f.position().top-d;h=parseInt(h*J/c);b=parseInt(b*l/d);ca(e,e.currentImg,a,h,b)}});f.mouseenter(function(){a.pauseOnMouseOver&&1<r&&e.firstLoadingComplete&&(e.mouseOverBanner=!0,clearTimeout(e.timeoutID),
nowx=(new Date).getTime(),e.timeElapsed+=nowx-e.arcInitialTime);a.autoHideNavArrows&&a.showNavArrows&&(t.css("display","block"),w.css("display","block"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(m.css({display:"block",left:parseInt((f.width()-R)/2,10)+"px"}),A.css({display:"block",left:parseInt(m.css("left").substring(0,m.css("left").length-2),10)-A.width()+"px"}),D.css({display:"block",left:parseInt(m.css("left").substring(0,m.css("left").length-2),10)+m.width()+parseInt(E.css("padding-left").substring(0,
E.css("padding-left").length-2),10)+"px"})):0>a.thumbsWrapperMarginBottom&&e.isVideoPlaying||!a.showBottomNav||(u.css({display:"block"}),u.stop().animate({opacity:1},500,"swing",function(){})))});f.mouseleave(function(){a.pauseOnMouseOver&&1<r&&e.firstLoadingComplete&&(e.mouseOverBanner=!1);a.autoHideNavArrows&&a.showNavArrows&&(t.css("display","none"),w.css("display","none"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(m.css("display","none"),A.css("display","none"),D.css("display",
"none")):u.stop().animate({opacity:0},300,"swing",function(){}));if(0<a.autoPlay&&1<r&&!e.isVideoPlaying&&a.pauseOnMouseOver&&e.firstLoadingComplete){clearTimeout(e.timeoutID);nowx=(new Date).getTime();e.arcInitialTime=(new Date).getTime();var c=parseInt(1E3*a.autoPlay-(e.timeElapsed+nowx-e.arcInitialTime),10);e.timeoutID=setTimeout(function(){H(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,y,v,x,z,u,m)},c)}});K=c(".contentHolderUnit",l);K.click(function(){var b=c(this).attr("rel");"true"==c(p[e.current_img_no]).attr("data-video")&&
(b!=e.current_img_no?e.isVideoPlaying=!1:(clearTimeout(e.timeoutID),C=c(this).find("img:first"),C.css("display","none"),B.css("display","none"),e.isVideoPlaying=!0,"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&u.css("display","none"),"bullets"==a.skin&&0<=a.thumbsWrapperMarginBottom&&m.css("display","none")));void 0!=c(p[e.current_img_no]).attr("data-link")&&b==e.current_img_no&&""!=c(p[e.current_img_no]).attr("data-link")&&(b=a.target,void 0!=c(p[e.current_img_no]).attr("data-target")&&
""!=c(p[e.current_img_no]).attr("data-target")&&(b=c(p[e.current_img_no]).attr("data-target")),"_blank"==b?window.open(c(p[e.current_img_no]).attr("data-link")):window.location=c(p[e.current_img_no]).attr("data-link"))});B.click(function(){B.css("display","none");clearTimeout(e.timeoutID);C=c("#contentHolderUnit_"+e.current_img_no,f).find("img:first");C.css("display","none");e.isVideoPlaying=!0;"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&u.css("display","none");"bullets"==
a.skin&&0<=a.thumbsWrapperMarginBottom&&m.css("display","none")});c(".parallax_mouseinteraction_texts",f).click(function(){if(void 0!=c(p[e.current_img_no]).attr("data-link")&&""!=c(p[e.current_img_no]).attr("data-link")&&!e.slideIsRunning){var b=a.target;void 0!=c(p[e.current_img_no]).attr("data-target")&&""!=c(p[e.current_img_no]).attr("data-target")&&(b=c(p[e.current_img_no]).attr("data-target"));"_blank"==b?window.open(c(p[e.current_img_no]).attr("data-link")):window.location=c(p[e.current_img_no]).attr("data-link")}});
t.click(function(){e.slideIsRunning||(e.isVideoPlaying=!1,e.previous_current_img_no=e.current_img_no,clearTimeout(e.timeoutID),H(-1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,y,v,x,z,u,m))});w.click(function(){e.slideIsRunning||(e.isVideoPlaying=!1,e.previous_current_img_no=e.current_img_no,clearTimeout(e.timeoutID),H(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,y,v,x,z,u,m))});var U=!1;c(window).resize(function(){var d=S();doResizeNow=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&
0==window.orientation&&(a.windowOrientationScreenSize0=c(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=c(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=c(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&c(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=!1),a.windowOrientationScreenSize90&&90==window.orientation&&c(window).height()>
a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&c(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==e.windowWidth&&(doResizeNow=!1,e.windowWidth=c(window).width()));-1!=d&&9==d&&0==e.windowWidth&&(doResizeNow=!1);e.windowWidth==c(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):e.windowWidth=
c(window).width();a.responsive&&doResizeNow&&(!1!==U&&clearTimeout(U),U=setTimeout(function(){var d=e,g=a,J=r,q=h,w=F,A=thumbsHolder_Thumbs,C=z;responsiveWidth=b.parent().parent().width();responsiveHeight=b.parent().parent().height();g.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());g.width100Proc&&(g.width=responsiveWidth);g.height100Proc&&(g.height=responsiveHeight);if(g.origWidth!=responsiveWidth||g.width100Proc){g.origWidth>responsiveWidth||
g.width100Proc?g.width=responsiveWidth:g.width100Proc||(g.width=g.origWidth);g.height100Proc||(g.height=g.width/d.bannerRatio);f.width(g.width);f.height(g.height);n.width(g.width);n.height(g.height);l.width(g.width);l.height(g.height);q.css("margin-top",parseInt((g.height-t.height())/2,10)+"px");V(p,g,b,J);contentHolderUnit=c(".contentHolderUnit",f);contentHolderUnit.width(g.width);contentHolderUnit.height(g.height);holderWidth=g.width*J;for(i=0;i<J;i++)P(i,d,g,p,f,b,q);l.width(holderWidth);"bullets"==
g.skin?0<=g.thumbsWrapperMarginBottom?m.css({left:parseInt((f.width()-m.width())/2,10)+"px",bottom:parseInt(g.thumbsWrapperMarginBottom/(g.origWidth/g.width),10)+"px",top:"auto"}):m.css({left:parseInt((f.width()-m.width())/2,10)+"px"}):Y(d,g,J,f,A,y,v,x,C,I,u);B.css({left:parseInt((g.width-B.width())/2,10)+"px",top:parseInt((g.height-B.height())/2,10)+"px"});clearTimeout(d.timeoutID);W(d.continuouseIntervalIDs);2>J?(c(".newFS",f).contents().unwrap(),N(d,d.currentImg,g,b,f,q,!1)):H(1,d,g,J,w,p,b,q,
l,f,B,A,y,v,x,C,u,m)}},300))});if("bullets"==a.skin){var F=c(".bottomNavButtonOFF",f);F.click(function(){if(!e.slideIsRunning&&e.firstLoadingComplete){e.isVideoPlaying=!1;var d=c(this).attr("rel");e.current_img_no!=d&&(c(F[e.current_img_no]).removeClass("bottomNavButtonON"),e.previous_current_img_no=e.current_img_no,"true"==c(p[e.previous_current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+e.previous_current_img_no,f).html(c(p[e.previous_current_img_no]).html()),P(e.previous_current_img_no,
e,a,p,f,b,h)),e.current_img_no=d-1,H(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,y,v,x,z,u,m))}});F.mouseenter(function(){var b=c(this),d=b.attr("rel");if(a.showPreviewThumbs){G=c('<div class="bottomOverThumb"></div>');b.append(G);var e=c(p[d]).attr("data-bottom-thumb"),f=c(p[T]).attr("data-bottom-thumb"),g=80,h=-80;T>d&&(g=-80,h=80);G.html("");G.html('<div class="innerBottomOverThumb"><img src="'+f+'"style="margin:0px;" id="oldThumb"><img src="'+e+'" style="margin-top:-80px; margin-left:'+g+'px;" id="newThumb"></div>');
c("#newThumb").stop().animate({marginLeft:"0px"},150,function(){G.html('<div class="innerBottomOverThumb"><img src="'+e+'"></div>')});c("#oldThumb").stop().animate({marginLeft:h+"px"},150,function(){});T=d}b.addClass("bottomNavButtonON")});F.mouseleave(function(){var b=c(this),d=b.attr("rel");a.showPreviewThumbs&&G.remove();e.current_img_no!=d&&b.removeClass("bottomNavButtonON")})}thumbsHolder_Thumbs.mousedown(function(){arrowClicked=!0;if(!e.effectIsRunning&&e.firstLoadingComplete){e.isVideoPlaying=
!1;var d=c(this).attr("rel");e.current_img_no!=d&&(c(thumbsHolder_Thumbs[e.current_img_no]).removeClass("thumbsHolder_ThumbON"),e.previous_current_img_no=e.current_img_no,"true"==c(p[e.previous_current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+e.previous_current_img_no,f).html(c(p[e.previous_current_img_no]).html()),P(e.previous_current_img_no,e,a,p,f,b,h)),e.bottomNavClicked=!0,e.current_img_no=d-1,H(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,y,v,x,z,u,m))}});thumbsHolder_Thumbs.mouseup(function(){arrowClicked=
!1});thumbsHolder_Thumbs.mouseenter(function(){var a=c(this);a.attr("rel");a.addClass("thumbsHolder_ThumbON")});thumbsHolder_Thumbs.mouseleave(function(){var a=c(this),b=a.attr("rel");e.current_img_no!=b&&a.removeClass("thumbsHolder_ThumbON")});v.click(function(){e.isCarouselScrolling||(currentCarouselLeft=y.css("left").substr(0,y.css("left").lastIndexOf("px")),0>currentCarouselLeft&&O(1,y,v,x,a,r,z,e))});x.click(function(){e.isCarouselScrolling||(currentCarouselLeft=y.css("left").substr(0,y.css("left").lastIndexOf("px")),
Math.abs(currentCarouselLeft-e.carouselStep)<(z.width()+e.thumbMarginLeft)*r&&O(-1,y,v,x,a,r,z,e))});"bullets"==a.skin?c(F[e.current_img_no]).addClass("bottomNavButtonON"):c(thumbsHolder_Thumbs[e.current_img_no]).addClass("thumbsHolder_ThumbON");setTimeout(function(){c(".myloader",f).css("display","none");V(p,a,b,r);e.firstLoadingComplete=!0;1<r&&(e.arcInitialTime=(new Date).getTime(),e.mouseOverBanner=!1,e.timeElapsed=0);N(e,e.currentImg,a,b,f,h,!1,e.current_img_no);0<a.autoPlay&&1<r&&(a.showCircleTimer&&
(e.intervalID=setInterval(function(){var b=e,c=a;nowx=(new Date).getTime();b.mouseOverBanner||b.effectIsRunning||!c.showCircleTimer||b.slideIsRunning||(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=c.behindCircleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth+2,b.ctx.strokeStyle=c.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=c.circleAlpha/
100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,(b.timeElapsed+nowx-b.arcInitialTime)/1E3*2/c.autoPlay*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth,b.ctx.strokeStyle=c.circleColor,b.ctx.stroke())},125)),e.timeoutID=setTimeout(function(){H(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,y,v,x,z,u,m)},1E3*a.autoPlay))},1E3*a.myloaderTime);"true"==c(p[e.current_img_no]).attr("data-video")&&B.css("display","block")})};c.fn.parallax_mouseinteraction.defaults=
{skin:"bullets",width:918,height:382,width100Proc:!1,height100Proc:!1,autoPlay:7,loop:!0,target:"_blank",absUrl:"",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,enableTouchScreen:!0,pauseOnMouseOver:!0,showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,responsive:!0,responsiveRelativeToBrowser:!1,
thumbsWrapperMarginBottom:-35,scrollSlideDuration:.8,scrollSlideEasing:"easeOutQuad",numberOfThumbsPerScreen:0,thumbsOnMarginTop:10,defaultEasing:"swing",myloaderTime:4,defaultExitLeft:0,defaultExitTop:0,defaultExitDuration:0,defaultExitDelay:0,defaultExitEasing:"swing",defaultExitOFF:!1,enableMouseInteraction:!0,maxInteractionXmove:70,maxInteractionYmove:40,mouseInteractionEasing:"easeOutQuint",mouseInteractionDuration:1,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origthumbsHolderWrapperH:0,
origWidthThumbsHolderVisibleWrapper:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);