/*
 * Parallax Ultra v1.5
 *
 * Copyright 2012-2017, LambertGroup
 * 
*/


(function(c){function Y(a,b,d){var h=K();d.responsive&&(newCss="",-1!=a.css("font-size").lastIndexOf("px")?(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px")),newCss+="font-size:"+fontSize/(d.origWidth/d.width)+"px;"):-1!=a.css("font-size").lastIndexOf("em")&&(fontSize=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),newCss+="font-size:"+fontSize/(d.origWidth/d.width)+"em;"),-1!=a.css("line-height").lastIndexOf("px")?(lineHeight=a.css("line-height").substr(0,
a.css("line-height").lastIndexOf("px")),newCss+="line-height:"+lineHeight/(d.origWidth/d.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(lineHeight=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),newCss+="line-height:"+lineHeight/(d.origWidth/d.width)+"em;"),a.wrapInner('<div class="newFS" style="'+newCss+'" />'));var f,n;f=a.attr("data-final-left");n=a.attr("data-final-top");d.responsive&&(f=parseInt(f/(d.origWidth/d.width),10),n=parseInt(n/(d.origWidth/d.width),
10));if("true"!=a.attr("data-preanimate")){var l=d.defaultEasing;""!=a.attr("data-easing")&&void 0!=a.attr("data-easing")&&(l=a.attr("data-easing"));d=1;1==b.isVideoPlaying&&(d=0);-1!=h&&9>h&&a.css({opacity:1});a.stop().animate({opacity:d,left:f+"px",top:n+"px"},1E3*a.attr("data-duration"),l,function(){1==b.isVideoPlaying&&c(b.currentImg.attr("data-text-id")).children().css("opacity",0)})}else a.css({left:f+"px",top:n+"px",opacity:1})}function T(a,b,d,h,f,n,l){b=c(b.attr("data-text-id")).children();
var g,q,t=0;currentText_arr=[];l&&c(".newFS",f).contents().unwrap();b.each(function(){currentText_arr[t]=c(this);var b=currentText_arr[t];l&&"true"==b.attr("data-preanimate")?(b.css({display:"block"}),g=b.attr("data-final-left"),q=b.attr("data-final-top"),d.responsive&&(g=parseInt(g/(d.origWidth/d.width),10),q=parseInt(q/(d.origWidth/d.width),10)),b.css({left:g+"px",top:q+"px",opacity:1,display:"block"})):l?b.css({display:"none",opacity:0}):b.css({display:"block"});"true"!=b.attr("data-preanimate")&&
(g=b.attr("data-initial-left"),q=b.attr("data-initial-top"),d.responsive&&(g=parseInt(g/(d.origWidth/d.width),10),q=parseInt(q/(d.origWidth/d.width),10)),b.css({left:g+"px",top:q+"px",opacity:parseInt(b.attr("data-fade-start"),10)/100}));l||(a.timeouts_arr[a.timeouts_arr.length]=setTimeout(function(){Y(b,a,d)},1E3*b.attr("data-delay")));t++})}function Z(a,b,d,h){d=c(a.currentImg.attr("data-text-id")).children();var f=0;currentText_arr=[];d.each(function(){currentText_arr[f]=c(this);var d=currentText_arr[f],
h=b.defaultExitLeft;void 0!=d.attr("data-exit-left")&&""!=d.attr("data-exit-left")&&(h=parseInt(d.attr("data-exit-left")/(b.origWidth/b.width),10));var g=b.defaultExitTop;void 0!=d.attr("data-exit-top")&&""!=d.attr("data-exit-top")&&(g=parseInt(d.attr("data-exit-top")/(b.origWidth/b.width),10));var q=b.defaultExitDuration;void 0!=d.attr("data-exit-duration")&&""!=d.attr("data-exit-duration")&&(q=parseFloat(d.attr("data-exit-duration")));var t=b.defaultExitDelay;void 0!=d.attr("data-exit-delay")&&
""!=d.attr("data-exit-delay")&&(t=parseFloat(d.attr("data-exit-delay")));var w=b.defaultExitEasing;void 0!=d.attr("data-exit-easing")&&""!=d.attr("data-exit-easing")&&(w=d.attr("data-exit-easing"));var m=b.defaultExitOFF.toString();void 0!=d.attr("data-exit-off")&&""!=d.attr("data-exit-off")&&(m=d.attr("data-exit-off"));"true"==m&&(q=0);0<q&&parseInt(d.attr("data-final-top")/(b.origWidth/b.width),10)==parseInt(d.css("top").substr(0,d.css("top").lastIndexOf("px")),10)?a.timeouts_arr[a.timeouts_arr.length]=
setTimeout(function(){d.stop().animate({left:h+"px",top:g+"px"},1E3*q,w,function(){"true"!=d.attr("data-preanimate")&&"false"==m?d.css({display:"none"}):(theLeft=d.attr("data-final-left"),theTop=d.attr("data-final-top"),b.responsive&&(theLeft=parseInt(theLeft/(b.origWidth/b.width),10),theTop=parseInt(theTop/(b.origWidth/b.width),10)),d.css({left:theLeft+"px",top:theTop+"px",opacity:1}))})},1E3*t):"true"!=d.attr("data-preanimate")&&"false"==m&&d.css({display:"none"});f++})}function W(a,b,d,h){for(k=
0;k<h;k++)d=c(a[k]),d=c(d.attr("data-text-id")).children(),currentText_arr=[],d.each(function(){currentText_arr[0]=c(this);var a=currentText_arr[0];if("true"==a.attr("data-preanimate")){a.css({display:"block"});var d=a.attr("data-final-left"),h=a.attr("data-final-top");b.responsive&&(d=parseInt(d/(b.origWidth/b.width),10),h=parseInt(h/(b.origWidth/b.width),10));a.css({left:d+"px",top:h+"px",opacity:1})}else a.css({display:"none"})})}function N(a){if(a)for(var b in a)a[b]&&clearTimeout(a[b]);a.length=
0}function aa(a,b,d,h){var f=K();if(0<a.bgArr.length){var n=0,l=0;bg_aux='<div class="parallax_ultra_all_bgArr">';for(x in a.bgArr){if(-1==f||-1!=f&&9<=f)bg_aux+='<div class="parallax_ultra_bgArr" style="background:url('+a.bgArr[x]+") repeat-x; width:"+a.width+"px; height:"+a.height+'px; left:0px"></div>';else{bg_aux+='<div class="parallax_ultra_bgArr" style="left:'+-1*h*a.width+"px; width:"+3*h*a.width+"px; height:"+a.height+'px;">';for(var l=Math.round(3*h*a.width/parseInt(a.bgIEWidth[n]/(a.origWidth/
a.width),10)+.5),g=0;g<l;g++)bg_aux+='<div class="parallax_ultra_bgArr_unit_IE78" style="width:'+parseInt(a.bgIEWidth[n]/(a.origWidth/a.width),10)+"px;height:"+a.height+'px;">&nbsp;</div>';bg_aux+="</div>"}n++}bg_aux+="</div>";b.append(bg_aux);c(".parallax_ultra_all_bgArr",d).css({width:a.width+"px",height:a.height+"px"});b=c(".parallax_ultra_bgArr",d);parseInt(100*a.height/a.origHeight,10);-1==f||-1!=f&&9<=f?b.css({"-webkit-background-size":"contain","-moz-background-size":"contain","-o-background-size":"contain",
"-ms-background-size":"contain","background-size":"contain"}):(n=0,b.each(function(){curBg=c(this);curBg.children().css({"-ms-filter":"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a.bgArr[n]+"', sizingMethod='scale')",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a.bgArr[n]+"', sizingMethod='scale')"});n++}))}}function ba(a,b,d,h,f,n){var l=K();if(0<a.bgArr.length){var g=0,q=0;c(".parallax_ultra_bgArr",b).each(function(){curBg=c(this);q="+="+(h.current_img_no-f)*parseInt(a.bgStep[g]/
(a.origWidth/a.width),10);n&&(q=0);-1==l||-1!=l&&9<=l?curBg.stop().animate({"background-position":q},1E3*a.bgDuration[g],a.bgEasing[g],function(){}):curBg.animate({left:q},1E3*a.bgDuration[g],a.bgEasing[g],function(){});g++})}}function ca(a,b,d,h){var f=K();0<a.bgArr.length&&(c(".parallax_ultra_all_bgArr",b).css({width:a.width+"px",height:a.height+"px"}),b=c(".parallax_ultra_bgArr",b),b.each(function(){curBg=c(this);curBg.css({width:3*d*a.width+"px",height:a.height+"px",left:-1*d*a.width+h.current_img_no*
a.bgStep[i]+"px"})}),a.responsive&&(parseInt(100*a.height/a.origHeight,10),-1==f||-1!=f&&9<=f?b.css({"-webkit-background-size":"contain","-moz-background-size":"contain","-o-background-size":"contain","-ms-background-size":"contain","background-size":"contain"}):(i=0,b.each(function(){curBg=c(this);curBg.children().css({width:parseInt(a.bgIEWidth[i]/(a.origWidth/a.width),10)+"px",height:a.height+"px","-ms-filter":"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a.bgArr[i]+"', sizingMethod='scale')",
filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+a.bgArr[i]+"', sizingMethod='scale')"});i++}))))}function I(a,b,d,h,f,n,l,g,q,t,w,m,C,G,H,u,J,z){var v=!0,y=!1,B;if(!d.loop&&b.current_img_no+a>=h||!d.loop&&0>b.current_img_no+a)v=!1;v&&!b.slideIsRunning&&b.firstLoadingComplete&&(b.slideIsRunning=!0,N(b.timeouts_arr),B=b.previous_current_img_no,c(b.currentImg.attr("data-text-id")).children().clearQueue(),Z(b,d,l,g),d.showCircleTimer&&(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),
b.ctx.beginPath(),b.ctx.globalAlpha=d.behindCircleAlpha/100,b.ctx.arc(d.circleRadius+2*d.circleLineWidth,d.circleRadius+2*d.circleLineWidth,d.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=d.circleLineWidth+2,b.ctx.strokeStyle=d.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=d.circleAlpha/100,b.ctx.arc(d.circleRadius+2*d.circleLineWidth,d.circleRadius+2*d.circleLineWidth,d.circleRadius,0,0,!1),b.ctx.lineWidth=d.circleLineWidth,b.ctx.strokeStyle=d.circleColor,b.ctx.stroke()),"bullets"==
d.skin?c(f[b.current_img_no]).removeClass("bottomNavButtonON"):c(m[b.current_img_no]).removeClass("thumbsHolder_ThumbON"),w.css("display","none"),b.current_img_no+a>=h?(b.current_img_no=0,y=!0):b.current_img_no=0>b.current_img_no+a?h-1:b.current_img_no+a,ba(d,t,h,b,B,y),d.showBottomNav&&("bullets"==d.skin?(d.autoHideBottomNav||z.css("display","block"),c(f[b.current_img_no]).addClass("bottomNavButtonON")):(d.autoHideBottomNav||J.css("display","block"),c(m[b.current_img_no]).addClass("thumbsHolder_ThumbON"),
currentCarouselLeft=C.css("left").substr(0,C.css("left").lastIndexOf("px")),0===b.current_img_no||b.current_img_no===h-1?P(0,C,G,H,d,h,u,b):P(1001,C,G,H,d,h,u,b))),b.currentImg=c(n[b.current_img_no]),q.animate({left:-1*b.current_img_no*d.width+"px"},1E3*d.scrollSlideDuration,d.scrollSlideEasing,function(){b.slideIsRunning=!1;b.arcInitialTime=(new Date).getTime();b.timeElapsed=0;"true"==c(n[b.current_img_no]).attr("data-video")&&w.css("display","block");"true"==c(n[b.previous_current_img_no]).attr("data-video")&&
(c("#contentHolderUnit_"+b.previous_current_img_no,t).html(c(n[b.previous_current_img_no]).html()),Q(b.previous_current_img_no,b,d,n,t,l,g));N(b.timeouts_arr);T(b,c(n[B]),d,l,t,g,!0);T(b,b.currentImg,d,l,t,g,!1);0<d.autoPlay&&1<h&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),b.timeoutID=setTimeout(function(){b.previous_current_img_no=b.current_img_no;I(1,b,d,h,f,n,l,g,q,t,w,m,C,G,H,u,J,z)},1E3*d.autoPlay))}))}function R(a,b,d,c,f){b=d.origImgsDimensions[b].split(";");c.responsive&&(b[0]/=c.origWidth/
c.width,b[1]/=c.origWidth/c.width);a.width(b[0]);a.height(b[1]);f&&c.width100Proc&&c.height100Proc&&a.css({position:"relative",left:parseInt(c.width-a.width(),10)+"px",top:parseInt(c.height-a.height(),10)+"px"})}function Q(a,b,d,h,f,n,l){d.responsive&&(imgInside=c("#contentHolderUnit_"+a,f).find("img:first"),null!=imgInside.width()&&R(imgInside,a,b,d,!0),textIdChildren=c(c(h[a]).attr("data-text-id")).children(),k=-1,textIdChildren.each(function(){k++;imgInside=c(this).find("img:first");null!=imgInside.width()&&
R(imgInside,c(h[a]).attr("data-text-id")+"-"+k,b,d,!1)}),c(c(h[a]).attr("data-text-id")).css({width:d.width+"px",left:parseInt(a*d.width,10),top:l.css("top")}))}function P(a,b,c,h,f,n,l,g){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?(g.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:"+="+a*g.carouselStep},500,"easeOutCubic",function(){O(g,b,c,h,f,n,l);g.isCarouselScrolling=!1})):currentCarouselLeft!=-1*Math.floor(g.current_img_no/
f.numberOfThumbsPerScreen)*g.carouselStep&&(g.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:-1*Math.floor(g.current_img_no/f.numberOfThumbsPerScreen)*g.carouselStep},500,"easeOutCubic",function(){O(g,b,c,h,f,n,l);g.isCarouselScrolling=!1}))}function O(a,b,c,h,f,n,l){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>currentCarouselLeft?c.hasClass("carouselLeftNavDisabled")&&c.removeClass("carouselLeftNavDisabled"):c.addClass("carouselLeftNavDisabled");
Math.abs(currentCarouselLeft-a.carouselStep)<(l.width()+a.thumbMarginLeft)*n?h.hasClass("carouselRightNavDisabled")&&h.removeClass("carouselRightNavDisabled"):h.addClass("carouselRightNavDisabled")}function X(a,b,d,h,f,n,l,g,q,t,w){"thumbs"==b.skin&&(w.css({bottom:parseInt(b.thumbsWrapperMarginBottom/(b.origWidth/b.width),10)+"px",top:"auto",height:parseInt(b.origthumbsHolderWrapperH/(b.origWidth/b.width),10)+"px"}),bgTopCorrection=0,l.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/
2+bgTopCorrection)+"px"),g.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),t.css("width",b.width-l.width()-g.width()),b.origWidthThumbsHolderVisibleWrapper=b.origWidth-l.width()-g.width(),f.css({width:parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/t.width()),10)+"px",height:parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/t.width()),10)+"px"}),b.numberOfThumbsPerScreen>=d&&t.css("left",parseInt((w.width()-(q.width()+a.thumbMarginLeft)*
d)/2,10)+"px"),c(".thumbsHolder_ThumbOFF",h).find("img:first").css({width:f.width()+"px",height:f.height()+"px","margin-top":parseInt((w.height()-f.height())/2,10)+"px"}),a.thumbMarginLeft=Math.floor((w.width()-l.width()-g.width()-q.width()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),thumb_i=-1,n.children().each(function(){thumb_i++;theThumb=c(this);theThumb.css("background-position","center "+b.thumbsOnMarginTop/(b.origWidth/b.width)+"px");0>=thumb_i?theThumb.css("margin-left",Math.floor((w.width()-
l.width()-g.width()-(a.thumbMarginLeft+theThumb.width())*(b.numberOfThumbsPerScreen-1)-theThumb.width())/2)+"px"):theThumb.css("margin-left",a.thumbMarginLeft+"px")}),a.carouselStep=(q.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen)}function K(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}c.fn.parallax_ultra=function(a){a=c.extend({},c.fn.parallax_ultra.defaults,a);return this.each(function(){var b=
c(this);responsiveWidth=b.parent().width();responsiveHeight=b.parent().height();a.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=responsiveWidth);a.origHeight=a.height;a.height100Proc&&(a.height=responsiveHeight);a.responsive&&(a.origWidth!=responsiveWidth||a.width100Proc)&&(a.width=a.origWidth>responsiveWidth||a.width100Proc?responsiveWidth:a.origWidth,a.height100Proc||(a.height=a.width/(a.origWidth/
a.origHeight)));var d=c("<div></div>").addClass("parallax_ultra").addClass(a.skin),h=c('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolderVisibleWrapper"><div class="contentHolder"></div></div>   <div class="playOver"></div>  <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <canvas class="mycanvas"></canvas>');b.wrap(d);b.after(h);var f=b.parent(".parallax_ultra"),
h=c(".bannerControls",f),n=c(".contentHolderVisibleWrapper",f),l=c(".contentHolder",f),d=c('<div class="bottomNavLeft"></div>'),g=c('<div class="bottomNav"></div>'),q=c('<div class="bottomNavRight"></div>');b.after(d);b.after(g);b.after(q);a.showAllControllers||h.css("display","none");var t=c(".leftNav",f),w=c(".rightNav",f);t.css("display","none");w.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(t.css("display","block"),w.css("display","block"));var m=c(".bottomNav",f),C=c(".bottomNavLeft",
f),G=c(".bottomNavRight",f),H;m.css("display","block");C.css("display","block");G.css("display","block");m.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});C.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});G.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});a.showBottomNav||(m.css("display","none"),C.css("display","none"),G.css("display","none"));a.showOnInitBottomNav||
(m.css("left","-5000px"),C.css("left","-5000px"),G.css("left","-5000px"));var u=c(".thumbsHolderWrapper",f),J=c(".thumbsHolderVisibleWrapper",f),z=c(".thumbsHolder",f),v,y;v=c('<div class="carouselLeftNav"></div>');y=c('<div class="carouselRightNav"></div>');u.append(v);u.append(y);y.css("right","0");z.css("width",v.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||u.css({opacity:0,display:"none"});"thumbs"==a.skin&&u.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+
"px",top:"auto"});a.enableTouchScreen&&f.swipe({swipe:function(a,b,c,d,f){e.effectIsRunning||("right"==b?t.click():w.click())}});var B=c(".playOver",f);B.css({left:parseInt((a.width-B.width())/2,10)+"px",top:parseInt((a.height-B.height())/2,10)+"px"});c(".myloader",f).css({left:(a.width-c(".myloader",f).width())/2+"px",top:(a.height-c(".myloader",f).height())/2+"px"});var d=K(),r=0,e={current_img_no:0,currentImg:0,previous_current_img_no:0,slideIsRunning:!1,mouseOverBanner:!1,isVideoPlaying:!1,carouselStep:0,
thumbMarginLeft:0,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,origImgsDimensions:[],firstLoadingComplete:!1,canvas:"",ctx:"",timeouts_arr:[],bannerRatio:a.origWidth/a.origHeight},U=0;e.canvas=c(".mycanvas",f)[0];e.canvas.width=2*a.circleRadius+4*a.circleLineWidth;e.canvas.height=2*a.circleRadius+4*a.circleLineWidth;-1!=d&&9>d&&(a.showCircleTimer=!1);a.showCircleTimer&&(e.ctx=e.canvas.getContext("2d"));f.width(a.width);f.height(a.height);n.width(a.width);
n.height(a.height);l.width(a.width);l.height(a.height);h.css("margin-top",parseInt((a.height-t.height())/2,10)+"px");var p=b.find("ul:first").children(),M,N=0,E,A,S=0,O=0,D;p.each(function(){e.currentImg=c(this);e.currentImg.is("li")||(e.currentImg=e.currentImg.find("li:first"));if(e.currentImg.is("li")){r++;M=c('<div class="contentHolderUnit" rel="'+(r-1)+'" id="contentHolderUnit_'+(r-1)+'">'+e.currentImg.html()+"</div>");M.width(a.width);M.height(a.height);l.append(M);N+=a.width;D=c("#contentHolderUnit_"+
(r-1),f).find("img:first");null!=D.width()?(e.origImgsDimensions[r-1]=D.width()+";"+D.height(),a.responsive&&a.origWidth!=responsiveWidth&&R(D,r-1,e,a,!0)):e.origImgsDimensions[r-1]=null;"bullets"==a.skin?(E=c('<div class="bottomNavButtonOFF" rel="'+(r-1)+'"></div>'),m.append(E),S+=parseInt(E.css("padding-left").substring(0,E.css("padding-left").length-2),10)+E.width(),O=parseInt((m.height()-parseInt(E.css("height").substring(0,E.css("height").length-2)))/2,10),E.css("margin-top",O+"px")):(image_name=
c(p[r-1]).attr("data-bottom-thumb"),A=c('<div class="thumbsHolder_ThumbOFF" rel="'+(r-1)+'"><img src="'+image_name+'"></div>'),z.append(A),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-v.width()-y.width())/A.width())),a.origThumbW=A.width(),a.origThumbH=A.height(),a.origthumbsHolderWrapperH=u.height(),e.thumbMarginLeft=Math.floor((a.origWidth-v.width()-y.width()-A.width()*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-1))),z.css("width",
z.width()+e.thumbMarginLeft+A.width()+"px"),thumbsHolder_MarginTop=parseInt((u.height()-parseInt(A.css("height").substring(0,A.css("height").length-2)))/2,10));l.append(c(e.currentImg.attr("data-text-id")));c(e.currentImg.attr("data-text-id")).css({width:a.width+"px",height:"100%",overflow:"hidden",left:parseInt((r-1)*a.width,10),top:h.css("top")});var b=-1;c(e.currentImg.attr("data-text-id")).children().each(function(){b++;D=c(this).find("img:first");null!=D.width()?(e.origImgsDimensions[e.currentImg.attr("data-text-id")+
"-"+b]=D.width()+";"+D.height(),a.responsive&&a.origWidth!=responsiveWidth&&R(D,e.currentImg.attr("data-text-id")+"-"+b,e,a,!1)):e.origImgsDimensions[e.currentImg.attr("data-text-id")+"-"+b]=null})}});l.width(N);"bullets"==a.skin?(m.width(S),a.showOnInitBottomNav&&(m.css("left",parseInt((f.width()-S)/2,10)+"px"),C.css("left",parseInt(m.css("left").substring(0,m.css("left").length-2),10)-C.width()+"px"),G.css("left",parseInt(m.css("left").substring(0,m.css("left").length-2),10)+m.width()+parseInt(E.css("padding-left").substring(0,
E.css("padding-left").length-2),10)+"px"))):(J.css({width:a.origWidth-v.width()-y.width(),left:v.width()+"px"}),e.carouselStep=(A.width()+e.thumbMarginLeft)*a.numberOfThumbsPerScreen,v.addClass("carouselLeftNavDisabled"),a.numberOfThumbsPerScreen>=r&&(y.addClass("carouselRightNavDisabled"),v.css("display","none"),y.css("display","none"),J.css("left",parseInt((u.width()-(A.width()+e.thumbMarginLeft)*r)/2,10)+"px")),c(".thumbsHolder_ThumbOFF",f).find("img:first").css("margin-top",thumbsHolder_MarginTop+
"px"),a.origthumbsHolder_MarginTop=thumbsHolder_MarginTop);thumbsHolder_Thumbs=c(".thumbsHolder_ThumbOFF",f);X(e,a,r,f,thumbsHolder_Thumbs,z,v,y,A,J,u);aa(a,b,f,r);c("iframe",f).each(function(){var a=c(this).attr("src"),b="?wmode=transparent";-1!=a.indexOf("?")&&(b="&wmode=transparent");c(this).attr("src",a+b)});e.current_img_no=0;e.currentImg=c(p[0]);f.mouseenter(function(){a.pauseOnMouseOver&&1<r&&e.firstLoadingComplete&&(e.mouseOverBanner=!0,clearTimeout(e.timeoutID),nowx=(new Date).getTime(),
e.timeElapsed+=nowx-e.arcInitialTime);a.autoHideNavArrows&&a.showNavArrows&&(t.css("display","block"),w.css("display","block"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(m.css({display:"block",left:parseInt((f.width()-S)/2,10)+"px"}),C.css({display:"block",left:parseInt(m.css("left").substring(0,m.css("left").length-2),10)-C.width()+"px"}),G.css({display:"block",left:parseInt(m.css("left").substring(0,m.css("left").length-2),10)+m.width()+parseInt(E.css("padding-left").substring(0,
E.css("padding-left").length-2),10)+"px"})):0>a.thumbsWrapperMarginBottom&&e.isVideoPlaying||!a.showBottomNav||(u.css({display:"block"}),u.stop().animate({opacity:1},500,"swing",function(){})))});f.mouseleave(function(){a.pauseOnMouseOver&&1<r&&e.firstLoadingComplete&&(e.mouseOverBanner=!1);a.autoHideNavArrows&&a.showNavArrows&&(t.css("display","none"),w.css("display","none"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(m.css("display","none"),C.css("display","none"),G.css("display",
"none")):u.stop().animate({opacity:0},300,"swing",function(){}));if(0<a.autoPlay&&1<r&&!e.isVideoPlaying&&a.pauseOnMouseOver&&e.firstLoadingComplete){clearTimeout(e.timeoutID);nowx=(new Date).getTime();e.arcInitialTime=(new Date).getTime();var c=parseInt(1E3*a.autoPlay-(e.timeElapsed+nowx-e.arcInitialTime),10);e.timeoutID=setTimeout(function(){I(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,z,v,y,A,u,m)},c)}});M=c(".contentHolderUnit",l);M.click(function(){var b=c(this).attr("rel");"true"==c(p[e.current_img_no]).attr("data-video")&&
(b!=e.current_img_no?e.isVideoPlaying=!1:(clearTimeout(e.timeoutID),D=c(this).find("img:first"),D.css("display","none"),B.css("display","none"),e.isVideoPlaying=!0,"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&u.css("display","none"),"bullets"==a.skin&&0<=a.thumbsWrapperMarginBottom&&m.css("display","none")));void 0!=c(p[e.current_img_no]).attr("data-link")&&b==e.current_img_no&&""!=c(p[e.current_img_no]).attr("data-link")&&(b=a.target,void 0!=c(p[e.current_img_no]).attr("data-target")&&
""!=c(p[e.current_img_no]).attr("data-target")&&(b=c(p[e.current_img_no]).attr("data-target")),"_blank"==b?window.open(c(p[e.current_img_no]).attr("data-link")):window.location=c(p[e.current_img_no]).attr("data-link"))});B.click(function(){B.css("display","none");clearTimeout(e.timeoutID);D=c("#contentHolderUnit_"+e.current_img_no,f).find("img:first");D.css("display","none");e.isVideoPlaying=!0;"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&u.css("display","none");"bullets"==
a.skin&&0<=a.thumbsWrapperMarginBottom&&m.css("display","none")});c(".parallax_ultra_texts",f).click(function(){if(void 0!=c(p[e.current_img_no]).attr("data-link")&&""!=c(p[e.current_img_no]).attr("data-link")&&!e.slideIsRunning){var b=a.target;void 0!=c(p[e.current_img_no]).attr("data-target")&&""!=c(p[e.current_img_no]).attr("data-target")&&(b=c(p[e.current_img_no]).attr("data-target"));"_blank"==b?window.open(c(p[e.current_img_no]).attr("data-link")):window.location=c(p[e.current_img_no]).attr("data-link")}});
t.click(function(){e.slideIsRunning||(e.isVideoPlaying=!1,e.previous_current_img_no=e.current_img_no,clearTimeout(e.timeoutID),I(-1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,z,v,y,A,u,m))});w.click(function(){e.slideIsRunning||(e.isVideoPlaying=!1,e.previous_current_img_no=e.current_img_no,clearTimeout(e.timeoutID),I(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,z,v,y,A,u,m))});var V=!1;c(window).resize(function(){var d=K();doResizeNow=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&
0==window.orientation&&(a.windowOrientationScreenSize0=c(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=c(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=c(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&c(window).width()>a.windowOrientationScreenSize0&&(doResizeNow=!1),a.windowOrientationScreenSize90&&90==window.orientation&&c(window).height()>
a.windowOrientationScreenSize90&&(doResizeNow=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&c(window).height()>a.windowOrientationScreenSize_90&&(doResizeNow=!1),0==e.windowWidth&&(doResizeNow=!1,e.windowWidth=c(window).width()));-1!=d&&9==d&&0==e.windowWidth&&(doResizeNow=!1);e.windowWidth==c(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):e.windowWidth=
c(window).width();a.responsive&&doResizeNow&&(!1!==V&&clearTimeout(V),V=setTimeout(function(){var d=e,g=a,L=r,q=h,w=F,C=thumbsHolder_Thumbs,D=A;responsiveWidth=b.parent().parent().width();responsiveHeight=b.parent().parent().height();g.responsiveRelativeToBrowser&&(responsiveWidth=c(window).width(),responsiveHeight=c(window).height());g.width100Proc&&(g.width=responsiveWidth);g.height100Proc&&(g.height=responsiveHeight);if(g.origWidth!=responsiveWidth||g.width100Proc){g.origWidth>responsiveWidth||
g.width100Proc?g.width=responsiveWidth:g.width100Proc||(g.width=g.origWidth);g.height100Proc||(g.height=g.width/d.bannerRatio);f.width(g.width);f.height(g.height);n.width(g.width);n.height(g.height);l.width(g.width);l.height(g.height);q.css("margin-top",parseInt((g.height-t.height())/2,10)+"px");W(p,g,b,L);contentHolderUnit=c(".contentHolderUnit",f);contentHolderUnit.width(g.width);contentHolderUnit.height(g.height);holderWidth=g.width*L;for(i=0;i<L;i++)Q(i,d,g,p,f,b,q);l.width(holderWidth);"bullets"==
g.skin?0<=g.thumbsWrapperMarginBottom?m.css({left:parseInt((f.width()-m.width())/2,10)+"px",bottom:parseInt(g.thumbsWrapperMarginBottom/(g.origWidth/g.width),10)+"px",top:"auto"}):m.css({left:parseInt((f.width()-m.width())/2,10)+"px"}):X(d,g,L,f,C,z,v,y,D,J,u);B.css({left:parseInt((g.width-B.width())/2,10)+"px",top:parseInt((g.height-B.height())/2,10)+"px"});clearTimeout(d.timeoutID);ca(g,f,L,d);I(1,d,g,L,w,p,b,q,l,f,B,C,z,v,y,D,u,m)}},300))});if("bullets"==a.skin){var F=c(".bottomNavButtonOFF",f);
F.click(function(){if(!e.slideIsRunning&&e.firstLoadingComplete){e.isVideoPlaying=!1;var d=c(this).attr("rel");e.current_img_no!=d&&(c(F[e.current_img_no]).removeClass("bottomNavButtonON"),e.previous_current_img_no=e.current_img_no,"true"==c(p[e.previous_current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+e.previous_current_img_no,f).html(c(p[e.previous_current_img_no]).html()),Q(e.previous_current_img_no,e,a,p,f,b,h)),e.current_img_no=d-1,I(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,z,v,
y,A,u,m))}});F.mouseenter(function(){var b=c(this),d=b.attr("rel");if(a.showPreviewThumbs){H=c('<div class="bottomOverThumb"></div>');b.append(H);var e=c(p[d]).attr("data-bottom-thumb"),f=c(p[U]).attr("data-bottom-thumb"),g=80,h=-80;U>d&&(g=-80,h=80);H.html("");H.html('<div class="innerBottomOverThumb"><img src="'+f+'"style="margin:0px;" id="oldThumb"><img src="'+e+'" style="margin-top:-80px; margin-left:'+g+'px;" id="newThumb"></div>');c("#newThumb").stop().animate({marginLeft:"0px"},150,function(){H.html('<div class="innerBottomOverThumb"><img src="'+
e+'"></div>')});c("#oldThumb").stop().animate({marginLeft:h+"px"},150,function(){});U=d}b.addClass("bottomNavButtonON")});F.mouseleave(function(){var b=c(this),d=b.attr("rel");a.showPreviewThumbs&&H.remove();e.current_img_no!=d&&b.removeClass("bottomNavButtonON")})}thumbsHolder_Thumbs.mousedown(function(){arrowClicked=!0;if(!e.effectIsRunning&&e.firstLoadingComplete){e.isVideoPlaying=!1;var d=c(this).attr("rel");e.current_img_no!=d&&(c(thumbsHolder_Thumbs[e.current_img_no]).removeClass("thumbsHolder_ThumbON"),
e.previous_current_img_no=e.current_img_no,"true"==c(p[e.previous_current_img_no]).attr("data-video")&&(c("#contentHolderUnit_"+e.previous_current_img_no,f).html(c(p[e.previous_current_img_no]).html()),Q(e.previous_current_img_no,e,a,p,f,b,h)),e.bottomNavClicked=!0,e.current_img_no=d-1,I(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,z,v,y,A,u,m))}});thumbsHolder_Thumbs.mouseup(function(){arrowClicked=!1});thumbsHolder_Thumbs.mouseenter(function(){var a=c(this);a.attr("rel");a.addClass("thumbsHolder_ThumbON")});
thumbsHolder_Thumbs.mouseleave(function(){var a=c(this),b=a.attr("rel");e.current_img_no!=b&&a.removeClass("thumbsHolder_ThumbON")});v.click(function(){e.isCarouselScrolling||(currentCarouselLeft=z.css("left").substr(0,z.css("left").lastIndexOf("px")),0>currentCarouselLeft&&P(1,z,v,y,a,r,A,e))});y.click(function(){e.isCarouselScrolling||(currentCarouselLeft=z.css("left").substr(0,z.css("left").lastIndexOf("px")),Math.abs(currentCarouselLeft-e.carouselStep)<(A.width()+e.thumbMarginLeft)*r&&P(-1,z,
v,y,a,r,A,e))});"bullets"==a.skin?c(F[e.current_img_no]).addClass("bottomNavButtonON"):c(thumbsHolder_Thumbs[e.current_img_no]).addClass("thumbsHolder_ThumbON");setTimeout(function(){c(".myloader",f).css("display","none");W(p,a,b,r);e.firstLoadingComplete=!0;e.arcInitialTime=(new Date).getTime();e.mouseOverBanner=!1;e.timeElapsed=0;T(e,e.currentImg,a,b,f,h,!1,e.current_img_no);0<a.autoPlay&&1<r&&(a.showCircleTimer&&(e.intervalID=setInterval(function(){var b=e,c=a;nowx=(new Date).getTime();b.mouseOverBanner||
b.effectIsRunning||!c.showCircleTimer||b.slideIsRunning||(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=c.behindCircleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,c.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth+2,b.ctx.strokeStyle=c.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),b.ctx.globalAlpha=c.circleAlpha/100,b.ctx.arc(c.circleRadius+2*c.circleLineWidth,c.circleRadius+2*c.circleLineWidth,
c.circleRadius,0,(b.timeElapsed+nowx-b.arcInitialTime)/1E3*2/c.autoPlay*Math.PI,!1),b.ctx.lineWidth=c.circleLineWidth,b.ctx.strokeStyle=c.circleColor,b.ctx.stroke())},125)),e.timeoutID=setTimeout(function(){I(1,e,a,r,F,p,b,h,l,f,B,thumbsHolder_Thumbs,z,v,y,A,u,m)},1E3*a.autoPlay))},1E3*a.myloaderTime);"true"==c(p[e.current_img_no]).attr("data-video")&&B.css("display","block")})};c.fn.parallax_ultra.defaults={skin:"bullets",width:918,height:382,width100Proc:!1,height100Proc:!1,autoPlay:7,loop:!0,target:"_blank",
absUrl:"",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,enableTouchScreen:!0,pauseOnMouseOver:!0,showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,responsive:!0,responsiveRelativeToBrowser:!1,thumbsWrapperMarginBottom:-35,scrollSlideDuration:.8,scrollSlideEasing:"easeOutQuad",
numberOfThumbsPerScreen:0,thumbsOnMarginTop:10,defaultEasing:"swing",myloaderTime:4,defaultExitLeft:0,defaultExitTop:0,defaultExitDuration:0,defaultExitDelay:0,defaultExitEasing:"swing",defaultExitOFF:!1,bgArr:[],bgIEWidth:[],bgStep:[],bgEasing:[],bgDuration:[],origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origthumbsHolderWrapperH:0,origWidthThumbsHolderVisibleWrapper:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);